"""Rename_columns_in_users_tables

Revision ID: 7d2ee4662e7a
Revises: 42376bffc1e4
Create Date: 2025-12-07 11:49:22.139557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2ee4662e7a'
down_revision: Union[str, Sequence[str], None] = '42376bffc1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_eamil'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_eamil'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
